language: c
compiler:
   - gcc

addons:
  apt:
   packages:
     - gcc-multilib
     - build-essential
     - autoconf
     - automake
     - libtool
     - texinfo
     - xorg-dev
     - libgtk2.0-dev
     - libjpeg-dev
     - libncurses-dev
     - libdbus-1-dev
     - libgif-dev
     - libtiff-dev
     - libm17n-dev
     - libpng12-dev
     - librsvg2-dev
     - libotf-dev
     - libxml2-dev
     - libatk-dev
     - libcairo-dev

script:
   - ./autogen.sh
   - ./configure --prefix=/tmp/emacs-prefix
   - make bootstrap
   - make install
   - make check
